In [1]:
# Import Packages
import pandas as pd

In [2]:
# Task 1
# Subtask 1.1
# Load the data
salary_df = pd.read_excel("2021_Salary Statistics by Employee.xlsx")
salary_df.head()

,Name,Sub Department,Empl Class Code,Pay Basis,Job FTE,Years in Job,Job Title,Working Title,Comp Rate,Annual Salary
0,"BECKER, JANE A",ACADEMIC AFFAIRS,CP,H,1.0,7.704110,UNIV EXEC STAFF ASST,UNIV EXEC STAFF ASST,27.64,57491.2
1,"CASE, JASMINE LEAH",ACADEMIC AFFAIRS,AS,A,1.0,0.027397,ADMIN PROGRAM SPEC,SPEC-STUDENT RET/ ENGAGE LRN,62000.00,62000.0
2,"ROZOWSKI, CASEY MATTHEW",ACADEMIC AFFAIRS,LI,A,1.0,1.120548,"DIR, UNSPECIFIED (10)","DIR MGMT, ANALYTICS, REPORTING",100000.00,100000.0
3,"JAMELSKE, STEPHANIE PASCOE",ACADEMIC AFFAIRS,LI,A,1.0,16.668493,ADMIN OFFICER/M,BUDGET OFFICER,100444.00,100444.0
4,"HOFFMAN, MARY F",ACADEMIC AFFAIRS,LI,A,1.0,1.205479,ASSOC VICE CHANCELLOR,INTERIM ASSOC VICE CHANCELLOR,144840.00,144840.0

In [3]:
salary_df.shape
salary_df.columns

Index(['Name', 'Sub Department', 'Empl Class Code', 'Pay Basis', 'Job FTE',
       'Years in Job', 'Job Title', 'Working Title', 'Comp Rate',
       'Annual Salary'],
      dtype='str')

In [4]:
longest_years_department = salary_df.loc[salary_df['Years in Job'].idxmax()]['Sub Department']
print(longest_years_department)

GEOGRAPHY & ANTHROPOLOGY

In [5]:
salary_df[salary_df['Sub Department'] == longest_years_department]['Annual Salary'].max()

np.float64(82468.0)

In [34]:
salary_df.loc[salary_df.loc[salary_df['Sub Department'] == 'MATHEMATICS']['Annual Salary'].idxmax()]['Job Title']

'PROFESSOR'

In [43]:
# Subtask 1.3
# For a given department, what is the "working title" of the highest-paid person?
def title_highest_paid(df: pd.DataFrame, deptname: str)->str:
    dept_df = df[df['Sub Department'] == deptname]
    highest_paid_working_title = dept_df.loc[dept_df['Annual Salary'].idxmax()]['Working Title']
    return str(highest_paid_working_title)

In [44]:
print(title_highest_paid(salary_df, 'MATHEMATICS'))
print(title_highest_paid(salary_df.iloc[0:3], 'ACADEMIC AFFAIRS'))
print(title_highest_paid(salary_df.iloc[100:105], 'ALUMNI RELATIONS'))

PROFESSOR
DIR MGMT, ANALYTICS, REPORTING
ATHLETICS/CORP DEVELOP SPEC

In [51]:
# For a given annual pay (a number), how many people make within a given range of that pay?
def num_ppl_within_pay(df: pd.DataFrame, target_pay: int, pay_range: int)-> int:
    min_val = target_pay - pay_range
    max_val = target_pay + pay_range
    return sum((df['Annual Salary'] >= min_val) & (df['Annual Salary'] <= max_val))

In [53]:
print(num_ppl_within_pay(salary_df, 42000, 1000))
print(num_ppl_within_pay(salary_df, 100000, 10000))
print(num_ppl_within_pay(salary_df, 300000, 50000))
print(num_ppl_within_pay(salary_df[salary_df['Sub Department']=='MUSIC AND THEATRE ARTS'], 100000, 10000))

43
74
1
1

In [77]:
# Subtask 1.3.3
# Which (sub) department has the most employees?
def largest_department(df: pd.DataFrame) -> str:
    largest_dept = df['Sub Department'].value_counts().idxmax()
    return str(largest_dept)

In [ ]:
largest_department(salary_df) == 'INTERCOLLEGIATE ATHLETICS'
largest_department(salary_df.iloc[0:300]) == 'ADVISING, RETEN & CAREER CNTR'

True

In [115]:
# Which (sub) department has the fewest employees? Return all of the department names as a series.
def smallest_department(df: pd.DataFrame) -> pd.Series:
    dept_employee_cnt = salary_df['Sub Department'].value_counts()
    min_employees = dept_employee_cnt.min()
    dept_cnt_boolean_series = dept_employee_cnt == min_employees
    return dept_cnt_boolean_series[dept_cnt_boolean_series].index.to_series()

In [118]:
dept_employee_cnt = salary_df['Sub Department'].value_counts()
min_employees = dept_employee_cnt.min()
dept_cnt_boolean_series = dept_employee_cnt == min_employees

sum(dept_cnt_boolean_series)

23

In [ ]:
# Subtask 1.3.5
# What is the ratio of the higest paid employee's salary to that of the lowest paid employee?
def max_pay_ratio(df: pd.DataFrame) -> int:
    highest_paid = salary_df['Annual Salary'].max()
    lowest_paid = salary_df['Annual Salary'].min()
    return highest_paid / lowest_paid

In [121]:
salary_df['Annual Salary'].max() / salary_df['Annual Salary'].min()

np.float64(9.746381540781993)

In [126]:
housing_master_df = pd.read_csv("HPI_master.csv")

In [129]:
# Make a new variable housing_df, containing only the records in the set for which the "level" is "MSA", and "hpi_flavor" is "all-transactions".
housing_df = housing_master_df[(housing_master_df['level'] == 'MSA') & (housing_master_df['hpi_flavor'] == 'all-transactions')]

In [133]:
housing_df.head()

,hpi_type,hpi_flavor,frequency,level,place_name,place_id,yr,period,index_nsa,index_sa
3770,traditional,all-transactions,quarterly,MSA,"Abilene, TX",10180,1986,2,107.53,NaN
3771,traditional,all-transactions,quarterly,MSA,"Abilene, TX",10180,1986,3,107.55,NaN
3772,traditional,all-transactions,quarterly,MSA,"Abilene, TX",10180,1986,4,94.27,NaN
3773,traditional,all-transactions,quarterly,MSA,"Abilene, TX",10180,1987,1,100.67,NaN
3774,traditional,all-transactions,quarterly,MSA,"Abilene, TX",10180,1987,2,100.46,NaN

In [ ]:
# Subtask 2.3.1
# For a given pair of a year and period (two integers in a tuple), which city / place had the highest price index (index_nsa)?
def place_with_highest_price(df: pd.DataFrame, time: tuple) -> str:
    yr, period = time
    yr_period_df =housing_df[(housing_df['yr'] == yr) & (housing_df['period'] == period)]
    city_high_price_index = yr_period_df.loc[yr_period_df['index_nsa'].idxmax()]['place_name']
    return str(city_high_price_index)

In [ ]:
time = (2022,1)
yr, period = time

yr_period_df =housing_df[(housing_df['yr'] == yr) & (housing_df['period'] == period)]
city_high_price_index = yr_period_df.loc[yr_period_df['index_nsa'].idxmax()]['place_name']

'Austin-Round Rock-Georgetown, TX'

In [ ]:
# For a given placename (string), in what (year,period) did the price index first go above a given price (float)?
def time_price_first_above(df: pd.DataFrame, place: str, price: float) -> tuple:
    matching = housing_df[(housing_df['place_name'] == place) & (housing_df['index_nsa'] > price)]
    row = matching.loc[matching.index[0]]
    return (row['yr'], row['period'])

In [150]:
place = 'Orlando-Kissimmee-Sanford, FL'
price = 200

matching = housing_df[(housing_df['place_name'] == place) & (housing_df['index_nsa'] > price)]
row = matching.loc[matching.index[0]]
thing = (row['yr'], row['period'])

type(thing)

tuple

In [ ]:
# For a given placename (string) and a pair of years & periods (two pairs of integers), what was the price change ratio?
def price_ratio(df: pd.DataFrame, place: str, t1: tuple, t2: tuple) -> float:
    year_1, period_1 = t1
    year_2, period_2 = t2

    price_2_df = df[(df['place_name'] == place) & (df['yr'] == year_2) & (df['period'] == period_2)]
    price_2 = price_2_df['index_nsa'].squeeze()

    price_1_df = df[(df['place_name'] == place) & (df['yr'] == year_1) & (df['period'] == period_1)]
    price_1 = price_1_df['index_nsa'].squeeze()
    return price_2 / price_1

In [157]:
place = 'Kokomo, IN'
t1 = (1999,1)
t2 = (2000,3)

year_1, period_1 = t1
year_2, period_2 = t2

price_2_df = housing_df[(housing_df['place_name'] == place) & (housing_df['yr'] == year_2) & (housing_df['period'] == period_2)]
price_2 = price_2_df['index_nsa'].squeeze()

price_1_df = housing_df[(housing_df['place_name'] == place) & (housing_df['yr'] == year_1) & (housing_df['period'] == period_1)]
price_1 = price_1_df['index_nsa'].squeeze()

price_2 / price_1

np.float64(1.045124439004488)