<img src="https://datasciencedegree.wisconsin.edu/wp-content/themes/data-gulp/images/logo.svg" width="300">
<img src="https://pandas.pydata.org/static/img/pandas.svg" width="200">

 # <center>Notebook - Lesson 6a - Filtering Data Frames </center>

It's really common to select data matching some condition using `pandas`.  This notebook teaches some of the pattern:

```
df[df[col]==val]
```

and more generally,

```
df[ logical condition ]
```

A book section is recommended 🐼:
* *Python for Data Analysis*, third edition: Section 5.2, subsection "Indexing, Selection, and Filtering", pages 142-147

---

## Imports up top

We'll start by importing NumPy and pandas:

In [1]:
import pandas as pd

##  Load data from file

I'm going to use the 2010-2019 weather data from the Chippewa Valley Regional Airport for this notebook.

If you get a message you get when running the following, set `low_memory = False` and run again.

In [2]:
weather_2010 = pd.read_csv('2010.csv')

C:\Users\benbr\AppData\Local\Temp\ipykernel_6348\3018874471.py:1: DtypeWarning: Columns (0: DailyPeakWindDirection, 1: DailyPeakWindSpeed, 2: DailySnowDepth, 3: HourlyAltimeterSetting, 4: HourlyDewPointTemperature, 5: HourlyDryBulbTemperature, 6: HourlySeaLevelPressure, 7: HourlyStationPressure, 8: HourlyWindGustSpeed, 9: HourlyWindSpeed, 10: MonthlyDaysWithGT001Precip, 11: MonthlyDepartureFromNormalPrecipitation, 12: MonthlyGreatestSnowDepth, 13: MonthlyGreatestSnowfall, 14: MonthlyGreatestSnowfallDate, 15: MonthlyTotalLiquidPrecipitation, 16: MonthlyTotalSnowfall, 17: ShortDurationEndDate005, 18: ShortDurationEndDate010, 19: ShortDurationEndDate015, 20: ShortDurationEndDate020, 21: ShortDurationEndDate030, 22: ShortDurationEndDate045, 23: ShortDurationEndDate060, 24: ShortDurationEndDate080, 25: ShortDurationEndDate100, 26: ShortDurationEndDate120, 27: ShortDurationEndDate150, 28: ShortDurationEndDate180) have mixed types. Specify dtype option on import or set low_memory=False.
  weather_2010 = pd.read_csv('2010.csv')

In [3]:
# run this cell to see a nice table of data.
weather_2010

,STATION,DATE,REPORT_TYPE,SOURCE,AWND,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,...,ShortDurationPrecipitationValue045,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset,WindEquipmentChangeDate
0,72643514991,2010-01-01T00:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
1,72643514991,2010-01-01T01:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
2,72643514991,2010-01-01T02:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
3,72643514991,2010-01-01T03:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
4,72643514991,2010-01-01T04:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124034,72643514991,2019-12-31T21:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
124035,72643514991,2019-12-31T22:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
124036,72643514991,2019-12-31T23:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
124037,72643514991,2019-12-31T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1634.0,2007-03-20
124038,72643514991,2019-12-31T23:59:00,SOM,6,6.7,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20

Notes:

* This data frame has 124 columns of data.
* There are 124039 rows of data.  Some rows are just before midnight, others are scattered throughout the day.

In [4]:
print(list(weather_2010.columns))

['STATION', 'DATE', 'REPORT_TYPE', 'SOURCE', 'AWND', 'BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'DailyAverageDewPointTemperature', 'DailyAverageDryBulbTemperature', 'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure', 'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature', 'DailyAverageWindSpeed', 'DailyCoolingDegreeDays', 'DailyDepartureFromNormalAverageTemperature', 'DailyHeatingDegreeDays', 'DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature', 'DailyPeakWindDirection', 'DailyPeakWindSpeed', 'DailyPrecipitation', 'DailySnowDepth', 'DailySnowfall', 'DailySustainedWindDirection', 'DailySustainedWindSpeed', 'DailyWeather', 'HDSD', 'HTDD', 'HourlyAltimeterSetting', 'HourlyDewPointTemperature', 'HourlyDryBulbTemperature', 'HourlyPrecipitation', 'HourlyPresentWeatherType', 'HourlyPressureChange', 'HourlyPressureTendency', 'HourlyRelativeHumidity', 'HourlySeaLevelPressure', 'HourlySkyConditions', 'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature', 'HourlyWindDirection', 'HourlyWindGustSpeed', 'HourlyWindSpeed', 'MonthlyAverageRH', 'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT0Temp', 'MonthlyDaysWithLT32Temp', 'MonthlyDepartureFromNormalAverageTemperature', 'MonthlyDepartureFromNormalCoolingDegreeDays', 'MonthlyDepartureFromNormalHeatingDegreeDays', 'MonthlyDepartureFromNormalMaximumTemperature', 'MonthlyDepartureFromNormalMinimumTemperature', 'MonthlyDepartureFromNormalPrecipitation', 'MonthlyDewpointTemperature', 'MonthlyGreatestPrecip', 'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth', 'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall', 'MonthlyGreatestSnowfallDate', 'MonthlyMaxSeaLevelPressureValue', 'MonthlyMaxSeaLevelPressureValueDate', 'MonthlyMaxSeaLevelPressureValueTime', 'MonthlyMaximumTemperature', 'MonthlyMeanTemperature', 'MonthlyMinSeaLevelPressureValue', 'MonthlyMinSeaLevelPressureValueDate', 'MonthlyMinSeaLevelPressureValueTime', 'MonthlyMinimumTemperature', 'MonthlySeaLevelPressure', 'MonthlyStationPressure', 'MonthlyTotalLiquidPrecipitation', 'MonthlyTotalSnowfall', 'MonthlyWetBulb', 'NormalsCoolingDegreeDay', 'NormalsHeatingDegreeDay', 'REM', 'REPORT_TYPE.1', 'SOURCE.1', 'ShortDurationEndDate005', 'ShortDurationEndDate010', 'ShortDurationEndDate015', 'ShortDurationEndDate020', 'ShortDurationEndDate030', 'ShortDurationEndDate045', 'ShortDurationEndDate060', 'ShortDurationEndDate080', 'ShortDurationEndDate100', 'ShortDurationEndDate120', 'ShortDurationEndDate150', 'ShortDurationEndDate180', 'ShortDurationPrecipitationValue005', 'ShortDurationPrecipitationValue010', 'ShortDurationPrecipitationValue015', 'ShortDurationPrecipitationValue020', 'ShortDurationPrecipitationValue030', 'ShortDurationPrecipitationValue045', 'ShortDurationPrecipitationValue060', 'ShortDurationPrecipitationValue080', 'ShortDurationPrecipitationValue100', 'ShortDurationPrecipitationValue120', 'ShortDurationPrecipitationValue150', 'ShortDurationPrecipitationValue180', 'Sunrise', 'Sunset', 'WindEquipmentChangeDate']

## Selecting data: where a column is a specific value

Let's find the rows in the `weather_2010` data frame that have a specific "REPORT_TYPE".  I'll arbitrarily choose one.

First, let's find out what types are available using the `.unique()` function:

In [5]:
weather_2010['REPORT_TYPE'].unique()

<StringArray>
['FM-15', 'FM-16', 'SOD  ', 'SOM  ']
Length: 4, dtype: str

Let's select the "SOD  " report type.  I find it annoying to have the spaces, but we'll just accept them for now.

We need to write a condition that produces True/False values, and feed that to the `[]` accessor operator for the data frame, in the canonical pattern for selecting data:

```
df[ boolean Series ]
```

In [6]:
# this produces True/False (booleans)
weather_2010['REPORT_TYPE']=='SOD  '

0         False
1         False
2         False
3         False
4         False
          ...
124034    False
124035    False
124036    False
124037     True
124038    False
Name: REPORT_TYPE, Length: 124039, dtype: bool

In [7]:
# next, stuff that inside [] to select just those rows with a True.  
# Note that this produces a temporaray data frame, and does not modify the original data

weather_2010[ weather_2010['REPORT_TYPE']=='SOD  ' ]
#             ^^  conditional statement        ^^
#          ^^  wrapped in square braces            ^^
# ^^ selects rows from the data frame where condition is True

,STATION,DATE,REPORT_TYPE,SOURCE,AWND,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,...,ShortDurationPrecipitationValue045,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset,WindEquipmentChangeDate
34,72643514991,2010-01-01T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1636.0,2007-03-20
59,72643514991,2010-01-02T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1637.0,2007-03-20
85,72643514991,2010-01-03T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1637.0,2007-03-20
111,72643514991,2010-01-04T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1638.0,2007-03-20
136,72643514991,2010-01-05T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1639.0,2007-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123843,72643514991,2019-12-27T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,743.0,1631.0,2007-03-20
123879,72643514991,2019-12-28T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,743.0,1632.0,2007-03-20
123940,72643514991,2019-12-29T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,743.0,1633.0,2007-03-20
124009,72643514991,2019-12-30T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1634.0,2007-03-20
124037,72643514991,2019-12-31T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1634.0,2007-03-20

The selected data using `weather_2010[ weather_2010['REPORT_TYPE']=='SOD  ' ]` appears to give us Sunrise and Sunset data:

In [8]:
weather_2010[ weather_2010['REPORT_TYPE']=='SOD  ' ][ ['DATE', 'Sunrise', 'Sunset'] ]
#                                                     ^^  a list of column names ^^
# ^^^  a temporary data frame of matching rows
#                                                   ^^accessing into temp df        ^^

                       DATE  Sunrise  Sunset
34      2010-01-01T23:59:00    744.0  1636.0
59      2010-01-02T23:59:00    744.0  1637.0
85      2010-01-03T23:59:00    744.0  1637.0
111     2010-01-04T23:59:00    744.0  1638.0
136     2010-01-05T23:59:00    744.0  1639.0
...                     ...      ...     ...
123843  2019-12-27T23:59:00    743.0  1631.0
123879  2019-12-28T23:59:00    743.0  1632.0
123940  2019-12-29T23:59:00    743.0  1633.0
124009  2019-12-30T23:59:00    744.0  1634.0
124037  2019-12-31T23:59:00    744.0  1634.0

[3652 rows x 3 columns]

Let's capture the result of this temporary, just with the sunrise and sunset data, and play a bit further:

In [9]:
sunrise_sunset = weather_2010[ weather_2010['REPORT_TYPE']=='SOD  ' ][ ['DATE','Sunrise', 'Sunset', 'DailyMinimumDryBulbTemperature', 'DailyMaximumDryBulbTemperature'] ]

Q: What is the earliest sunrise?

In [10]:
sunrise_sunset['Sunrise'].min()

np.float64(419.0)

Q: On what day is the earliest sunrise?

In [12]:
row_of_first_earliest = sunrise_sunset['Sunrise'].argmin()
#                                                 ^^ argmin gets the row index of the (first) min

sunrise_sunset['DATE'].iloc[row_of_first_earliest]
#                           ^^ use that row index to get the row
#             ^^ and get the date
# ^^ from the data frame

'2010-06-11T23:59:00'

Q: How many days in this data frame have this same sunrise time? (4:19am, but encoded weird)

In [13]:
sum(sunrise_sunset['Sunrise']==sunrise_sunset['Sunrise'].min())
#    ^^ produce a Series of True/False, where the sunrise == min 
# ^^ then take sum -- True is 1, False is 0, so summing is counting.

100

Q: On what day is the latest sunset?

In [14]:
row_of_first_latest = sunrise_sunset['Sunset'].argmax()
sunrise_sunset['DATE'].iloc[row_of_first_latest]
#             ^^^^ use the date column
#                          ^^ use the index we stored of the (first) latest sunset

'2010-06-21T23:59:00'

Q: What was the high temperature on that date?

In [15]:
sunrise_sunset['DailyMaximumDryBulbTemperature'].iloc[row_of_first_latest]

np.float64(79.0)

I find it relieving that the latest sunset occurs on the summer solstice.  Satisfied sigh.

Now your turn.

🧠 On what date was the (first) earliest **sunset**?

In [16]:
# 🧠 your code here
row_of_first_earliest_sunset = sunrise_sunset['Sunset'].argmin()
#                                                 ^^ argmin gets the row index of the (first) min

sunrise_sunset['DATE'].iloc[row_of_first_earliest_sunset]
#                           ^^ use that row index to get the row
#             ^^ and get the date
# ^^ from the data frame

'2010-12-04T23:59:00'

🧠 What was the *minimum* dry bulb tempurature on the day of the (first) earliest sunset?

In [17]:
# 🧠 your code here
sunrise_sunset['DailyMaximumDryBulbTemperature'].iloc[row_of_first_earliest_sunset]

np.float64(26.0)

## Selecting data: using "greater than"

Let's select the rows of the data frame where the `DailyMaximumDryBulbTemperature` is greater than 80.


The pattern is:

```
df[ df[colname] > 80]
```

In [18]:
weather_2010[ weather_2010['DailyMaximumDryBulbTemperature']>80 ]
#             ^^ conditional producing booleans             ^^^
#           ^^ [] to access into the complete data frame        ^^
# produces a temporary variable with the requested data

,STATION,DATE,REPORT_TYPE,SOURCE,AWND,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,...,ShortDurationPrecipitationValue045,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset,WindEquipmentChangeDate
3057,72643514991,2010-04-01T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,547.0,1833.0,2007-03-20
3418,72643514991,2010-04-14T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524.0,1850.0,2007-03-20
4461,72643514991,2010-05-19T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,433.0,1932.0,2007-03-20
4486,72643514991,2010-05-20T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432.0,1933.0,2007-03-20
4590,72643514991,2010-05-23T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,429.0,1936.0,2007-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120189,72643514991,2019-09-18T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,548.0,1811.0,2007-03-20
120241,72643514991,2019-09-19T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549.0,1810.0,2007-03-20
120308,72643514991,2019-09-20T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550.0,1808.0,2007-03-20
120445,72643514991,2019-09-24T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,555.0,1800.0,2007-03-20
120607,72643514991,2019-09-30T23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602.0,1749.0,2007-03-20

🧠 How many days in this decade of data had a "Daily maximum dry bulb temperature" less than 32 degrees???

(On how many days was the high temperature less than freezing?)

In [25]:
# 🧠 Your code here
sum(weather_2010['DailyMaximumDryBulbTemperature'] <32)

721

## Selecting data: using a helper lambda: Observations in the month of December

Let's choose to find the data from the month of December. 

The pattern to select is 

```
df[ condition on df ]
```

We need to find a condition on a column of the data frame that gives us "the month is December".  I'll guide you through it.

### Getting a single entry to play with

I like to start figuring out how to write my selector by getting a single value in memory.  We get data from a DataFrame using the `[]` accessor operator.

In [26]:
d = weather_2010['DATE'][0]
# d for date.
# [0] to get the top one.

# now we'll have variable `d` to play with.

In [27]:
# try this, it will fail:  (until you run the next cell, after which it will succeed)
d.month

AttributeError: 'str' object has no attribute 'month'

You should have gotten an error:

`AttributeError: 'str' object has no attribute 'month'`

Indeed, strings don't have months.  I'll convert the column to a datetime column so that I have datetimes instead of strings, cuz then I don't have to write silly string parsing code to extract the month form the string.

In [28]:
# do the conversion
weather_2010['DATE'] = pd.to_datetime(weather_2010['DATE'])
#                       ^^ conversion to datetime
#  ^^^ overwrite the same column with new data

In [29]:
# get the 0th entry again.  this time, it's a datetime.
d = weather_2010['DATE'][0]

In [30]:
# this time, succeeds.
d.month

1

We can see that the month is an integer from 1 to 12, with 1 being January and 12 being December.  

Turning back to our objective, "get the data from December", we need to write an expression that tests if the month is 12.  Again, the pattern to select data in a pandas data frame is 

```
df[ condition on df ]
```

In [31]:
# I *want* to write this, but it won't work
weather_2010[weather_2010['DATE'].month == 12]

AttributeError: 'Series' object has no attribute 'month'

I can't just go `.month`, unfortunately.  I need to write a little function (a lambda) to get the month and test if it's equal to 12.  I'm going to use the `map` function to have pandas call the function for every element in the data frame.

In [32]:
weather_2010[weather_2010['DATE'].map(lambda d: d.month) == 12]
#                                     ^^^  gets the month
#                                ^^^ map calls lambda for every element
#                                                        ^^^ tests if equal to 12
#            ^^^ uses a column of True and False values to select the desired rows from the data frame.

,STATION,DATE,REPORT_TYPE,SOURCE,AWND,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,...,ShortDurationPrecipitationValue045,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset,WindEquipmentChangeDate
11234,72643514991,2010-12-01 00:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
11235,72643514991,2010-12-01 01:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
11236,72643514991,2010-12-01 02:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
11237,72643514991,2010-12-01 03:13:00,FM-16,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
11238,72643514991,2010-12-01 03:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124034,72643514991,2019-12-31 21:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
124035,72643514991,2019-12-31 22:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
124036,72643514991,2019-12-31 23:56:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20
124037,72643514991,2019-12-31 23:59:00,SOD,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,1634.0,2007-03-20
124038,72643514991,2019-12-31 23:59:00,SOM,6,6.7,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-03-20

Let's save the December data into a variable:

In [33]:
december_data = weather_2010[weather_2010['DATE'].map(lambda d: d.month) == 12]

🧠 What was the minimum "daily maximum dry bulb tempurature" in all December days from 2010 to 2019?

In [35]:
# 🧠 your code here
december_data['DailyMinimumDryBulbTemperature'].min()

np.float64(-22.0)

---

Credits: Written by silviana amethyst, phd.  fall 2023.